In [24]:
# get version of any lib
import numpy as np
print(np.__version__)

1.26.4


In [1]:
#write a program to get help with a function in numpy
import numpy as np
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [31]:
# write a numpy program to test if any of the elements of a given array are non zero
import numpy as np
x = np.array([1,2,3,4])
print("original array:")
print(x)
print(np.any(x))


original array:
[1 2 3 4]
True


In [23]:
# write a program to test element wise positive or negative infinty
import numpy as np
array = np.array([1,-2,np.inf,-np.inf,0,3.5])
print("original array")
print(array)
result_pos_inf = np.isposinf(array)
result_neg_inf = np.isneginf(array)
print("result_pos_inf is",result_pos_inf)
print("result_neg_inf is",result_neg_inf)


original array
[ 1.  -2.   inf -inf  0.   3.5]
result_pos_inf is [False False  True False False False]
result_neg_inf is [False False False  True False False]


In [18]:
# write a python program to test element wise for NaN(Not a number of a given array )
import numpy as np
a = np.array([1,0,np.nan,np.inf])
print(a)
print("test elementwise to NaN:")
print(np.isnan(array))



[ 1.  0. nan inf]
test elementwise to NaN:
[False False  True False]


In [32]:
# write a python program to create an array of even integers from 30 to 70
import numpy as np
array = np.arange(30,71,21)
print(array)

[30 51]


In [19]:
# write a  python program to create an array of integers from 30 to 70
import numpy as np
array = np.arange (30,71)
print(array)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [20]:
# write a pyhton program to create 3*3 identity matrix
import numpy as np
array = np.identity(3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
# write a program to perform addition , substraction , multiplication of two matrix
import numpy as np
array1 = np.array([1,3,5,7,5,4])
array2 = np.array([8,5,9,5,5,6])
add = np.add(array1,array2)
print(add)

[ 9  8 14 12 10 10]


In [29]:
# write a program to reverse 4*4 array
import numpy as np
array = np.array([[1,2,3,4],[5,6,7,8],[9,0,1,2],[4,6,2,8]])
print ('original array')
print (array)
print('reversed array')
print(array[::-1])

original array
[[1 2 3 4]
 [5 6 7 8]
 [9 0 1 2]
 [4 6 2 8]]
reversed array
[[4 6 2 8]
 [9 0 1 2]
 [5 6 7 8]
 [1 2 3 4]]


In [30]:
# write a pyhton program to transpose given 4*4 matrix
import numpy as np
array = np.array([[1,2,3,4],[5,6,7,8],[9,0,1,2],[4,6,2,8]])
print ('original array')
print (array)
print('transposed array')
print(np.transpose(array))

original array
[[1 2 3 4]
 [5 6 7 8]
 [9 0 1 2]
 [4 6 2 8]]
transposed array
[[1 5 9 4]
 [2 6 0 6]
 [3 7 1 2]
 [4 8 2 8]]


In [36]:
# write a python program to create a new array from a given array from swapping first and last , second and third column
import numpy as np
array = np.arange(16,32).reshape(4,4)
print ('original array')
print (array)
array[:,[0,3]] = array[:,[3,0]]
print('swapped array')
print(array)
array[:,[1,2]] = array[:,[2,0]]
print('swapped array')
print(array)

original array
[[16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
swapped array
[[19 17 18 16]
 [23 21 22 20]
 [27 25 26 24]
 [31 29 30 28]]
